spring.application.name=nomad-backend
google.sheet.id=1xLj6HdF5G1iAXp_ApPH0FwMrm5MweTFfrHp1rsiiDBo
google.credentials.path=classpath:google-credentials.json

spring.datasource.url=jdbc:postgresql://localhost:5432/nomad_db
spring.datasource.username=postgres
spring.datasource.password=selcan12
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=myVeryStrongSecretKeyForJwtAuthentication
jwt.expires-in=15m
jwt.expiration=900000
refresh.token.expires-days=7
jwt.refresh-expiration=604800000
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile